baseURL = "https://www.schabrechtsk.be"
languageCode = "en"
title = "SchabrechtsK - Independent software developer & Technical Lead"
theme = "anatole"
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[params]
    title = "I'm Kenneth Schabrechts"
    description = "Independent software developer & Technical Lead"
    author = "Kenneth Schabrechts"
    profilePicture = "images/profile.png"
    # Twitter card support
    images = ["images/site-feature-image.png"]
    show_reading_time = true
    favicon = "favicons/"
    # Animations are default shown so turn off here by setting to true
    doNotLoadAnimations = false
    # Keywords for SEO
    keywords = "SchabrechtsK, Kenneth Schabrechts, Independent software developer, Technical Lead"
    # Date Formats
    singleDateFormat = "02 Jan 2006"
    indexDateFormat = "02 Jan 2006"
    listDateFormat = "02 Jan 2006"
    # Content Ratio: How much % should the content take up. Default: 0.6
    contentratio = 0.65
    # What is the main section where the content is?
    mainSections = ["post"]
    # Declare Custom CSS style
    customCss = ["css/custom.css"]
    # Old Content Warning
    oldContentWarning = true
    oldContentDuration = 365
    # Google Site Verify
    googleSiteVerify = "YIVl9Kw1qbS11D80Ga3M_u1nIXrrcy7TCb-m9YjEOs8"

    # Socials
    # use 'fab' when brand icons, use 'fas' when standard solid icons.
    [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/SchabrechtsK"

    [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/schabrechtsk"

    [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "Linkedin"
    url = "https://www.linkedin.com/in/schabrechtsk/"

    [[params.socialIcons]]
    icon = "fab fa-youtube"
    title = "YouTube"
    url = "https://www.youtube.com/channel/UCEJxHRVVF3bLrv6XANtcPbQ"

    [[params.socialIcons]]
    icon = "fab fa-twitch"
    title = "Twitch"
    url = "https://twitch.tv/SchabrechtsK"

    [[params.socialIcons]]
    icon = "fab fa-instagram"
    title = "instagram"
    url = "https://www.instagram.com/schabrechtsk/"

    [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "e-mail"
    url = "mailto:kenneth@schabrechtsk.be"

[menu]
    [[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/"

    [[menu.main]]
    name = "Archive"
    weight = 200
    identifier = "posts"
    url = "/posts/"

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"