baseURL = "https://www.schabrechtsk.be"
languageCode = "en"
title = "SchabrechtsK - Independent software developer & Technical Lead"
theme = "anatole"
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[params]
    title = "I'm Kenneth Schabrechts"
    description = "Independent software developer & Technical Lead"
    author = "Kenneth Schabrechts"
    profilePicture = "images/profile.png"
    show_reading_time = true
    favicon = "favicons/"
    doNotLoadAnimations = false
    # Date Formats
    singleDateFormat = "02 Jan 2006"
    indexDateFormat = "02 Jan 2006"
    listDateFormat = "02 Jan 2006"
    # Content Ratio: How much % should the content take up. Default: 0.6
    contentratio = 0.65
    # What is the main section where the content is?
    mainSections = ["post"]
    ## Math settings
    [math]
    enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
    use = "katex"  # options: "katex", "mathjax". default is "katex".

    # Socials
    # use 'fab' when brand icons, use 'fas' when standard solid icons.
    [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/SchabrechtsK"

    [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/schabrechtsk"

    [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "Linkedin"
    url = "https://www.linkedin.com/in/schabrechtsk/"

    [[params.socialIcons]]
    icon = "fab fa-youtube"
    title = "YouTube"
    url = "https://www.youtube.com/channel/UCEJxHRVVF3bLrv6XANtcPbQ"

    [[params.socialIcons]]
    icon = "fab fa-twitch"
    title = "Twitch"
    url = "https://twitch.tv/SchabrechtsK"

    [[params.socialIcons]]
    icon = "fab fa-instagram"
    title = "instagram"
    url = "https://www.instagram.com/schabrechtsk/"

    [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "e-mail"
    url = "mailto:kenneth@schabrechtsk.be"


    # TODO: ALL BELOW THIS PART!
#    # Keywords for SEO
#     keywords = ""
#
#    # Twitter card support
#     images = ["images/site-feature-image.png"]
#
#     # Form Spree Contact Form
#     #contactFormAction = "https://formspree.io/f/your-form-hash-here"
#     # Google Site Verify
#     #googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"